name: 'Mega Deploy'
description: 'example of a composite action'
inputs:
  deploy-role:
    description: ARN of the role to assume for deployment
    required: true
  docker-image:
    description: Docker image uri to deploy
    required: true
  deploy-env:
    description: Environment name to deploy to
    required: true
  tf-dir:
    description: Directory containing the terraform to run
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.docker-image }}.
      shell: bash
    - run: echo Hello ${{ inputs.deploy-env }}.
      shell: bash
    - run: echo Hello ${{ inputs.deploy-role }}.
      shell: bash
    - run: echo Hello ${{ inputs.tf-dir }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Terraform Validate
      working-directory: ${{ inputs.tf-dir }}
      run: terraform validate
      shell: bash
